### PR TITLE
Add properties to App Container

### PR DESCRIPTION
**Pull request by cbaconnier**
`(int)$app->required_age;` About this one, Steam seems to returns only `0`  or `"18"` I choose to cast it to int keep some consistency.

### CODE REVIEW

**Comment by stygiansabyss** [comment]
I will be happy to merge this in.  Could you update the example response for this with how the new fields appear?

Thanks!

**Comment by stygiansabyss** [comment]
I am slightly concerned by the properties with no data.  Primarily appId, but others as well (isFree should show something no matter what).

Do you know if its just an error of the output or if it is actually empty/null?

**Comment by cbaconnier** [comment]
`fullgame->appid` was added from a previous PR https://github.com/syntaxerrors/Steam/commit/d91a7c9409fd148685c4d5db68fb7d963daaa1f5
The "fake object fullgame" was not present in the response until now, since the method did not had the return statement.
In the case of portal2, `appid` will be null since it's already the "parent" game. But, if you take an another app, like a DLC, it can have a parent and his appid will be set.

isFree is actually returning false but `print_r` doesn't display it. I would recommend `var_dump` for your example since you get more information.

Only my opinon: I prefer empty data instead of something like `$price->final = 'No price found';`  because it's easier to manipulate afterward when we expect a double (or null) but get a string. The same goes with `website`, if it's null or empty string, we know it doesn't have one.

And thanks for your works, you saved me a lot of time 😄

**Comment by stygiansabyss** [comment]
2.0.13 tagged with this change added in.

**Pull request merged**
