### PR TITLE
Add support for Laravel 9

### PR DESCRIPTION
**Pull request by bensherred**
This adds support for Laravel 9 and also updates the GitHub workflow to test against PHP 8.1.

### CODE REVIEW

**Comment by nicekiwi** [comment]
May not be as simple as appears, but I will look into this soon as I can :) cheers for the PR

**Comment by nicekiwi** [comment]
> Any updates on the PR?

My bad, crazy busy. I have started work on it. Thanks for reminder. :)

**Comment by chescos** [comment]
Hey @nicekiwi - any news on the progress? I don't want to annoy you, I understand you're busy. If you point me towards what needs to be updated to make this package work with L9, I can also help with this PR.

**Comment by bensherred** [comment]
Hey @nicekiwi, just wondering if you had been able to take a look at this or if you would like me to make some changes?

**Comment by bensherred** [comment]
@nicekiwi any updates on this?

**Comment by nicekiwi** [comment]
@bensherred sorry for the super slow responses. I've implemented Laravel9 support in the `laravel9` branch, could you try that? `"syntax/steam-api": "dev-laravel9"`

**Comment by bensherred** [comment]
Hey @nicekiwi, that’s great! I’ll take a look over the weekend and let you know

**Comment by chescos** [comment]
Hey, any news on a stable release for L9?

**Pull request closed without merging**
