### PR TITLE
Add information about the gameserver if the player is connected to one

### PR DESCRIPTION
**Pull request by Decicus**
As documented under "Private data" for [GetPlayerSummaries](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29)

### CODE REVIEW

**Comment by Metrakit** [comment]
Very useful ! Thanks

**Comment by stygiansabyss** [comment]
I can't merge until the examples are updated to match the new data.  If you can do it, great.  If not, it will have to wait until I have time to devote to it.

**Comment by Decicus** [comment]
That's alright 👍

I'll see if I'm able to look into that some time during this week.

**Comment by Decicus** [comment]
I completely forgot about this. My bad.

Thanks for merging! 😄

**Comment by stygiansabyss** [comment]
Np.   Probably making some small changes before tagging a release.

**Pull request merged**
