### PR TITLE
Fix Laravel 4 compatibility

### PR DESCRIPTION
**Pull request by MaartenStaa**
Re-added missing package() call in Service Provider

### CODE REVIEW

**Comment by stygiansabyss** [comment]
Thanks :)

**Comment by MaartenStaa** [comment]
Could you please also tag a new release? Thanks!

**Comment by stygiansabyss** [comment]
I did.  1.2.3 is up.

**Comment by MaartenStaa** [comment]
You did? I don't see it on the [Releases](https://github.com/syntaxerrors/Steam/releases) page, and composer update doesn't see an available update.

**Comment by stygiansabyss** [comment]
https://github.com/syntaxerrors/Steam/releases/tag/1.2.3.  Packagist show it as well.

**Comment by stygiansabyss** [comment]
Fixed the release.  Should be able to grab it soon.

**Comment by MaartenStaa** [comment]
It worked now. Thanks again!

**Pull request merged**
