### PR TITLE
Update dependencies and add support for Laravel 8

### PR DESCRIPTION
**Pull request by bensherred**
This PR adds support for Laravel 8 (resolving #109) and updates the composer dependencies to the latest version.

## Changelog

- Minimum PHP version is now 7.3
- Added support for Laravel 8
- Updated Guzzle to v7.0.1
- Updated PHPUnit to v9.3
- Updated orchestra testbench to v6.0
- Updated phpdotenv to v5.2
- Updated the format of the config file

> Note: Due to the number of core changes, it might be worth releasing a major version due to no longer supporting Laravel 5.8.

### CODE REVIEW

**Comment by bensherred** [comment]
@stygiansabyss how are you setting/handling the Steam API Key for Travis CI?

**Review by ShawnCZek — APPROVED** [review]

**Comment by nicekiwi** [comment]
@bensherred the API key is saved as an ENV variable in the Travis settings. If it's failing Shawn's key may have expired.

**Comment by nicekiwi** [comment]
Hmm updated the key to mine and still fails. The Steam API may have changed, assuming the ENV method is still the same. That's a worry.

**Comment by nicekiwi** [comment]
Tests are still passing on Master, i'll check out the code and have a look.

**Comment by bensherred** [comment]
All the tests work locally (made sure of that before committing) but doesn’t seem to work on Travis CI

**Comment by nicekiwi** [comment]
@bensherred ok from what I can see in the Travis docs: https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml

"Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository."

As your PR is from a fork, not a direct PR on the BASE repo the build wont have access to the API key. 

I'm happy to merge this now and trigger a packagist release.

**Comment by nicekiwi** [comment]
@bensherred Thank you for your contribution 🌮 😃

**Comment by bensherred** [comment]
No worries at all @nicekiwi, glad I could help!

**Pull request merged**
